### PR TITLE
Website structure and firebase connection

### PR DESCRIPTION
**Pull request by Farahkh**
I have added firebase config and did a test query.
I created the header and footer section template.

### CODE REVIEW

**Review by Stef-GMS — CHANGES_REQUESTED** [review]
Rejecting per request

**Comment by Stef-GMS** [comment]
pubspec.yaml needs to have dev_dependencies updated.

Remove 
`jaspr_web_compilers: ^4.0.4`
Add
`build_web_compilers: ^4.0.5`

**Review by Stef-GMS — CHANGES_REQUESTED** [review]
The serif font doesn't match the sans-serif font and is hard to read with Dyslexia.

Please change the header font from 

`font-family: "Rosarivo", serif;`

to 

`font-family: "Roboto", sans-serif;`

**Comment by Farahkh** [comment]
Usually we choose 2 fonts one for heading and one is used for the body
text, I can suggest another font for heading.

**Comment by Stef-GMS** [comment]
That's OK.  Please use a Sans-Serif font.

**Pull request merged**
